//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationMateriales.srvEmpleados {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Empleado", Namespace="http://schemas.datacontract.org/2004/07/CPM.Empleados.Servicio.Entidades")]
    [System.SerializableAttribute()]
    public partial class Empleado : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DepartamentoIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EdadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SexoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DepartamentoId {
            get {
                return this.DepartamentoIdField;
            }
            set {
                if ((this.DepartamentoIdField.Equals(value) != true)) {
                    this.DepartamentoIdField = value;
                    this.RaisePropertyChanged("DepartamentoId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Edad {
            get {
                return this.EdadField;
            }
            set {
                if ((this.EdadField.Equals(value) != true)) {
                    this.EdadField = value;
                    this.RaisePropertyChanged("Edad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Sexo {
            get {
                return this.SexoField;
            }
            set {
                if ((object.ReferenceEquals(this.SexoField, value) != true)) {
                    this.SexoField = value;
                    this.RaisePropertyChanged("Sexo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="srvEmpleados.IsrvEmpleados")]
    public interface IsrvEmpleados {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvEmpleados/ObtenerEmpleadosPorDeptoId", ReplyAction="http://tempuri.org/IsrvEmpleados/ObtenerEmpleadosPorDeptoIdResponse")]
        WebApplicationMateriales.srvEmpleados.Empleado[] ObtenerEmpleadosPorDeptoId(int deptoId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvEmpleados/ObtenerEmpleadosPorDeptoId", ReplyAction="http://tempuri.org/IsrvEmpleados/ObtenerEmpleadosPorDeptoIdResponse")]
        System.Threading.Tasks.Task<WebApplicationMateriales.srvEmpleados.Empleado[]> ObtenerEmpleadosPorDeptoIdAsync(int deptoId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvEmpleados/InsertaEmpleados", ReplyAction="http://tempuri.org/IsrvEmpleados/InsertaEmpleadosResponse")]
        void InsertaEmpleados(WebApplicationMateriales.srvEmpleados.Empleado oItem);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvEmpleados/InsertaEmpleados", ReplyAction="http://tempuri.org/IsrvEmpleados/InsertaEmpleadosResponse")]
        System.Threading.Tasks.Task InsertaEmpleadosAsync(WebApplicationMateriales.srvEmpleados.Empleado oItem);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvEmpleados/ObtenerUnEmpleadoPorId", ReplyAction="http://tempuri.org/IsrvEmpleados/ObtenerUnEmpleadoPorIdResponse")]
        WebApplicationMateriales.srvEmpleados.Empleado ObtenerUnEmpleadoPorId(int empleadoId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvEmpleados/ObtenerUnEmpleadoPorId", ReplyAction="http://tempuri.org/IsrvEmpleados/ObtenerUnEmpleadoPorIdResponse")]
        System.Threading.Tasks.Task<WebApplicationMateriales.srvEmpleados.Empleado> ObtenerUnEmpleadoPorIdAsync(int empleadoId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvEmpleados/ObtenerDepartamentos", ReplyAction="http://tempuri.org/IsrvEmpleados/ObtenerDepartamentosResponse")]
        System.Data.DataSet ObtenerDepartamentos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvEmpleados/ObtenerDepartamentos", ReplyAction="http://tempuri.org/IsrvEmpleados/ObtenerDepartamentosResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> ObtenerDepartamentosAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IsrvEmpleadosChannel : WebApplicationMateriales.srvEmpleados.IsrvEmpleados, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IsrvEmpleadosClient : System.ServiceModel.ClientBase<WebApplicationMateriales.srvEmpleados.IsrvEmpleados>, WebApplicationMateriales.srvEmpleados.IsrvEmpleados {
        
        public IsrvEmpleadosClient() {
        }
        
        public IsrvEmpleadosClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public IsrvEmpleadosClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IsrvEmpleadosClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IsrvEmpleadosClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WebApplicationMateriales.srvEmpleados.Empleado[] ObtenerEmpleadosPorDeptoId(int deptoId) {
            return base.Channel.ObtenerEmpleadosPorDeptoId(deptoId);
        }
        
        public System.Threading.Tasks.Task<WebApplicationMateriales.srvEmpleados.Empleado[]> ObtenerEmpleadosPorDeptoIdAsync(int deptoId) {
            return base.Channel.ObtenerEmpleadosPorDeptoIdAsync(deptoId);
        }
        
        public void InsertaEmpleados(WebApplicationMateriales.srvEmpleados.Empleado oItem) {
            base.Channel.InsertaEmpleados(oItem);
        }
        
        public System.Threading.Tasks.Task InsertaEmpleadosAsync(WebApplicationMateriales.srvEmpleados.Empleado oItem) {
            return base.Channel.InsertaEmpleadosAsync(oItem);
        }
        
        public WebApplicationMateriales.srvEmpleados.Empleado ObtenerUnEmpleadoPorId(int empleadoId) {
            return base.Channel.ObtenerUnEmpleadoPorId(empleadoId);
        }
        
        public System.Threading.Tasks.Task<WebApplicationMateriales.srvEmpleados.Empleado> ObtenerUnEmpleadoPorIdAsync(int empleadoId) {
            return base.Channel.ObtenerUnEmpleadoPorIdAsync(empleadoId);
        }
        
        public System.Data.DataSet ObtenerDepartamentos() {
            return base.Channel.ObtenerDepartamentos();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ObtenerDepartamentosAsync() {
            return base.Channel.ObtenerDepartamentosAsync();
        }
    }
}
